/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author h-fat
 */
public class adminpage extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public adminpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Usersbutton = new javax.swing.JButton();
        welcomelabel = new javax.swing.JLabel();
        adbutton = new javax.swing.JButton();
        bookingsbutton = new javax.swing.JButton();
        housesrbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        myinformationbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setPreferredSize(new java.awt.Dimension(670, 530));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(680, 530));
        jPanel3.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Administrator");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(180, 40, 320, 70);

        Usersbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Usersbutton.setText("Users");
        Usersbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(Usersbutton);
        Usersbutton.setBounds(70, 310, 160, 60);
        Usersbutton.getAccessibleContext().setAccessibleName("Add User");

        welcomelabel.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        welcomelabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomelabel.setText("Welcome to Administrator Page");
        jPanel3.add(welcomelabel);
        welcomelabel.setBounds(70, 130, 400, 50);

        adbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adbutton.setText("Advertisment");
        adbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(adbutton);
        adbutton.setBounds(260, 400, 160, 60);

        bookingsbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bookingsbutton.setText("Bookings");
        bookingsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingsbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(bookingsbutton);
        bookingsbutton.setBounds(260, 310, 160, 60);

        housesrbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        housesrbutton.setText("Houses");
        housesrbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housesrbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(housesrbutton);
        housesrbutton.setBounds(70, 400, 160, 60);

        logoutbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoutbutton.setText("logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(logoutbutton);
        logoutbutton.setBounds(450, 400, 160, 60);

        myinformationbutton.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        myinformationbutton.setText("my information");
        myinformationbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myinformationbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(myinformationbutton);
        myinformationbutton.setBounds(450, 310, 160, 60);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleName("Add User");
        jPanel3.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsersbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersbuttonActionPerformed
        //user button
        // TODO add your handling code here:
    	
    	userspage up = new userspage();
    	this.setVisible(false);
    	up.setVisible(true);
    	
    	
    }//GEN-LAST:event_UsersbuttonActionPerformed

    private void adbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adbuttonActionPerformed
        //Advertisment button
        // TODO add your handling code here:
    }//GEN-LAST:event_adbuttonActionPerformed

    private void bookingsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingsbuttonActionPerformed
        //booking button        
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingsbuttonActionPerformed

    private void housesrbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housesrbuttonActionPerformed
        //houses button
        // TODO add your handling code here:
    }//GEN-LAST:event_housesrbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        //logoutbutton        
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void myinformationbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myinformationbuttonActionPerformed
        //my information button        
        // TODO add your handling code here:
    }//GEN-LAST:event_myinformationbuttonActionPerformed
    
    
    public void setname(String name) {
    	jLabel18.setText(name);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Usersbutton;
    private javax.swing.JButton adbutton;
    private javax.swing.JButton bookingsbutton;
    private javax.swing.JButton housesrbutton;
    
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton myinformationbutton;
    private javax.swing.JLabel welcomelabel;
    // End of variables declaration//GEN-END:variables
}
